# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabotapp', '0006_auto_20170821_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='user',
        ),
        migrations.AddField(
            model_name='shift',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
