# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0007_auto_20171007_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tag',
            field=models.TextField(blank=True, help_text=b'Event tag of service'),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
